#!/bin/sh
####################################################
#                                                   #
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗    #
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║    #
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║    #
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║    #
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║    #
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝    #
#####################################################

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg

###### DUAL MONITOR ######
bspc monitor DVI-D-2 -d 1 2 3 4 5
bspc monitor HDMI-1 -d  6 7 8 9 0

###### SINGLE MONITOR ######
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

########## Border Colors #################
bspc config focused_border_color "#2E3440"
bspc config normal_border_color "#2E3440"

#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

######### Program settings ################
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a discord desktop='^3'
bspc rule -a Firefox desktop='^2'
bspc rule -a brave desktop='^6'
bspc rule -a VSCodium desktop='^7'
bspc rule -a Thunderbird desktop='^2'
bspc rule -a Nicotine desktop='^5'
bspc rule -a Ledger Live desktop='^9'
bspc rule -a KeePassXC desktop='^4'

bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a Arcolinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Arcolinux-calamares-tool.py state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating

######### Other Settings ################
xsetroot -cursor_name left_ptr &
xbacklight -set 30

########## Window Settings ##############
bspc config border_width         2
bspc config window_gap           10  
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50 
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

######## MY picom :) ###################
picom  &

######### My Bar ###############
polybar main 

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window